### ISSUE TITLE
Open-source the elm app

### ISSUE THREAD

**Issue by iancanderson** [thoughtbot/PurpleTrainElm#61]
- [x] Prepare:
  - [x] Cache alerts on backend so we don't make as many requests to MBTA (https://github.com/thoughtbot/purple_train_web/issues/44)
  - [x] Make sure no sensitive data in git repo history
  - [x] Choose open source license, commit in repo (https://github.com/thoughtbot/PurpleTrainElm/pull/62)
  - [x] Improve README/documentation (https://github.com/thoughtbot/PurpleTrainElm/pull/64)
  - [ ] (nice-to-have) make it easier to setup/install - WIP branch here: https://github.com/thoughtbot/PurpleTrainElm/compare/ia-elm-github-install
- [x] Make github repo public
- [x] Announce on blog

**Comment by jyurek** [comment]
Status of this, @iancanderson?

**Comment by iancanderson** [comment]
Announcement blog post is live https://robots.thoughtbot.com/purple-train-is-open-source
